<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_fiskal_model extends CI_Model
{

    public $table = 'surat_fiskal';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('no_seri', $q);
	$this->db->or_like('no_surat', $q);
	$this->db->or_like('nomor_polisi', $q);
	$this->db->or_like('nama_pemilik', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('merktype_kendaraan', $q);
	$this->db->or_like('tahuncc_kendaraan', $q);
	$this->db->or_like('warna_kendaraan', $q);
	$this->db->or_like('nomor_chasis', $q);
	$this->db->or_like('nomor_mesin', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('bbn_kb_sebesar', $q);
	$this->db->or_like('tanggal_bbn_kb', $q);
	$this->db->or_like('pkb_sebesar', $q);
	$this->db->or_like('tanggal_pkb', $q);
	$this->db->or_like('daerah_tujuan', $q);
	$this->db->or_like('untuk_atas_nama', $q);
	$this->db->or_like('alamat_pemilik', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('no_swdkllj', $q);
	$this->db->or_like('tanggal_swdkllj', $q);
	$this->db->or_like('tanggal_akhir_berlaku_swdkllj', $q);
	$this->db->or_like('pejabat_uptd', $q);
	$this->db->or_like('pejabat_jasaraharja', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('no_seri', $q);
	$this->db->or_like('no_surat', $q);
	$this->db->or_like('nomor_polisi', $q);
	$this->db->or_like('nama_pemilik', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('merktype_kendaraan', $q);
	$this->db->or_like('tahuncc_kendaraan', $q);
	$this->db->or_like('warna_kendaraan', $q);
	$this->db->or_like('nomor_chasis', $q);
	$this->db->or_like('nomor_mesin', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('bbn_kb_sebesar', $q);
	$this->db->or_like('tanggal_bbn_kb', $q);
	$this->db->or_like('pkb_sebesar', $q);
	$this->db->or_like('tanggal_pkb', $q);
	$this->db->or_like('daerah_tujuan', $q);
	$this->db->or_like('untuk_atas_nama', $q);
	$this->db->or_like('alamat_pemilik', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('no_swdkllj', $q);
	$this->db->or_like('tanggal_swdkllj', $q);
	$this->db->or_like('tanggal_akhir_berlaku_swdkllj', $q);
	$this->db->or_like('pejabat_uptd', $q);
	$this->db->or_like('pejabat_jasaraharja', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_fiskal_model.php */
/* Location: ./application/models/Surat_fiskal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-19 10:10:48 */
/* http://harviacode.com */